### ISSUE TITLE
White page on chrome during login

### ISSUE THREAD

**Issue by kiwiapple87** [fatcat4096/MSF2CSV#11]
After the initial run of this script when I try to run it again and it attempts to log into MSF i get this white page on chrome.

![MSF2CSV error](https://github.com/fatcat4096/MSF2CSV/assets/14914799/835283e1-d37f-4c1f-afd9-f2d77f0c0786)

All I am doing is double clicking the msf2csv.py file. This only started happening after my initial run of the script that worked.

**Comment by fatcat4096** [comment]
Hi! I'm thinking this stems from the logging code trying to create a trace directory somewhere in your Windows system directories instead of locally. Please grab a fresh copy of this code. I'm uploading a patch for the log_utils.py routines that ensure these attempt to create /trace/ locally instead.

Also, please ping me on Discord  -- my user ID is fatcat4096

**Comment by fatcat4096** [comment]
Seems resolved.
